### PR TITLE
Fixes Issue 544: Added path to save `celerybeat-schedule` file

### LINKED ISSUE #544: [BUG] Backend: Celery beat schedule file created in project working directory
**Describe the bug**

Celery Beat saves its `celerybeat-schedule` file in the container’s working
directory by default. Since this directory also contains the application source
code, this gets mixed with the project files.
This behavior can pollute the source tree inside the container and may lead to accidental commits or confusion.

**To Reproduce**

Start the application using Docker Compose.
Run all the services as usual.
A `celerybeat-schedule` file is created inside the `buffalogs/` folder.

**Expected behaviour** 

Celery Beat should save its schedule file outside the application working
directory, in a dedicated location intended for storing temporary files. 
This change does not affect task scheduling logic or runtime behavior. 

Happy to submit a PR if this change is acceptable.

### PR DESCRIPTION
**Pull request by rshaurya**
This PR fixes #544 by adding a custom path to save the `celerybeat-schedule` which is created by Celery Beat.

**Screenshots**

Screenshot from 2026-01-23 21-06-04

Screenshot from 2026-01-23 21-06-35

### CODE REVIEW

File: buffalogs/run_beat.sh [hunk 1]
```diff
@@ -1,3 +1,3 @@
 #!/bin/bash
 
-celery -A buffalogs beat
\ No newline at end of file
+celery -A buffalogs beat --schedule /tmp/celerybeat-schedule
```
Comment (Lorygold) [inline buffalogs/run_beat.sh]: if you put the file in the `/tmp/` folder, the definition of `.gitignore` is not valid, right? 
maybe the current celery execution could be left as it was and just adding the file to the `.gitignore` solves the problem, what do you think?

Comment (rshaurya) [reply buffalogs/run_beat.sh]: Yes, adding the file to the`.gitignore` works too. I saved the file in `/tmp/` directory so that a fresh `celerybeat-schedule` file is created on restart and this keeps the working directory clean. 

Shall I move forward with `.gitignore`?

Comment (rshaurya) [reply buffalogs/run_beat.sh]: Hi @Lorygold ,

As per our discussion, only the `gitignore` file has been changed and the beat file is unchanged.

**Review by Lorygold — APPROVED** [review]
